import type { Metadata } from "next";
import { Header } from "@/components/Header/Header";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { SnackbarProvider } from "@/context/SnackbarContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <SnackbarProvider>
            <Header />
            <main style={{ paddingTop: "96px" }}>{children}</main>
          </SnackbarProvider>
        </CartProvider>
      </body>
    </html>
  );
}
